Support metro s3 dashed target name (no dash in folder name)

diff --git a/.github/workflows/release-offline.yml b/.github/workflows/release-offline.yml
--- a/.github/workflows/release-offline.yml
+++ b/.github/workflows/release-offline.yml
@@ -193,6 +193,18 @@ jobs:
           board_name=${board_name%_noota}
           # Remove 'wippersnapper_' prefix if present
           board_name=${board_name#wippersnapper_}
+          # check folder name exists, otherwise do replace of underscore with dash, or blank
+          if [ ! -d "ws-boards/boards/${board_name}" ]; then
+            if [ -d "ws-boards/boards/${board_name//_/-}" ]; then
+              board_name=${board_name//_/-}
+            elif [ -d "ws-boards/boards/${board_name//_//}" ]; then
+              board_name=${board_name//_//}
+            else
+              echo "Error: Board definition folder ws-boards/boards/${board_name} does not exist."
+              exit 1
+            fi
+          fi
+          # check again if folder exists, otherwise replace underscore with blank
           content=$(cat ws-boards/boards/${board_name//_/-}/definition.json)
           {
             echo 'boardJson<<EOF'
