Skip tinyuf2 manual merge_bin if no esptool secction in board definition

diff --git a/.github/workflows/release-offline.yml b/.github/workflows/release-offline.yml
--- a/.github/workflows/release-offline.yml
+++ b/.github/workflows/release-offline.yml
@@ -203,6 +203,11 @@ jobs:
         id: get_tinyuf2
         continue-on-error: true
         run: |
+          # check ${{fromJson(steps.get_board_json.outputs.boardJson).esptool.flashMode}} is not empty
+          if [ -z "${{fromJson(steps.get_board_json.outputs.boardJson).esptool.flashMode}}" ]; then
+            echo "Error: esptool.flashMode is not set in board definition."
+            exit 1
+          fi
           BOARD_NAME="${{fromJson(steps.get_board_json.outputs.boardJson).bootloaderBoardName}}"
           for attempt in 1 2; do
             echo "Attempt $attempt: Fetching tinyuf2 release info for board $BOARD_NAME"
